---
name: Test
"on":
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # coverage action needs a nightly toolchain
      # @Swatinem/fucov needs with llvm-tools
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          # components: llvm-tools-preview

      # runs cargo with defaults flags, using the default `lcov` output
      # uses: Swatinem/fucov@v1

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast  # Customize args for your own needs
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'

      - name: Run coverage
        id: coverage
        uses: actions-rs/grcov@v0.1

      - name: Fix coverage action output
        id: strip-linefeed
        run: |
          export stripped=$(echo ${{ steps.coverage.outputs.report }} | tr -d '\n')
          echo ::set-output name=filename::$stripped

      - name: Move coverage file
        run: |
          mv ${{ steps.strip-linefeed.outputs.filename }} ./coverage.xml

      - name: Report test coverage to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        with:
          key: rust
          coverage-file: coverage.xml
          dsn: ${{ secrets.DEEPSOURCE_DSN }}
          fail-ci-on-error: true
